In [8]:
import numpy as np

In [10]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [12]:
print((type)(lista))
print((type)(array))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [21]:
## Matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
##Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [31]:
print('Maximo', notas.max())
print('Minimo', notas.min())
print('Desvio padrao', notas.std())
print('Media', notas.mean())
print('Posicao menor', notas.argmin())

Maximo 9.8
Minimo 5.6
Desvio padrao 1.5628179676469045
Media 7.76
Posicao menor 1
